# Generated by Django 3.1.5 on 2021-03-31 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WIZ', '0002_auto_20210227_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='votes',
            new_name='choice_number',
        ),
    ]
